### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CH-Meme** [pepeteam/pepecoin#56]
When I input "make -f makefile.unix USE_UPNP=-"

I get this....

root@Sup:~# cd pepecoin/src
root@Sup:~/pepecoin/src# make -f makefile.unix USE_UPNP=-
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -g -DBOOST_SPIRIT_THREADSAFE -I/root/pepecoin/src -I/root/pepecoin/src/obj -DENABLE_WALLET -I/root/pepecoin/src/secp256k1/include -I/root/pepecoin/src/leveldb/include -I/root/pepecoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
In file included from alert.h:9,
                 from alert.cpp:5:
serialize.h:19:10: fatal error: boost/type_traits/is_fundamental.hpp: No such file or directory
   19 | #include <boost/type_traits/is_fundamental.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile.unix:218: obj/alert.o] Error 1

**Comment by theronic** [comment]
Getting the same error trying to build on MacOS Sonoma 14.3, following the [build-osx.md docs](https://github.com/pepeteam/pepecoin/blob/master/src/doc/build-osx.md?plain=1):

```
src git:(master) make -f makefile.osx
clang++ -c -Wall -Wextra -Wformat -Wno-ignored-qualifiers -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -Wno-deprecated-declarations -g -DMAC_OSX -DMSG_NOSIGNAL=0 -DBOOST_SPIRIT_THREADSAFE -DENABLE_WALLET -DUSE_UPNP=1 -I/Users/petrus/Code/pepecoin/src/secp256k1/include -I/Users/petrus/Code/pepecoin/src/leveldb/include -I/Users/petrus/Code/pepecoin/src/leveldb/helpers -DHAVE_BUILD_INFO -I"/Users/petrus/Code/pepecoin/src" -I"/Users/petrus/Code/pepecoin/src"/obj -I"/usr/local/include" -I"/usr/local/Cellar/boost/1.59.0/include" -I"/usr/local/Cellar/berkeley-db4/4.8.30/include" -I"/usr/local/openssl-1.0.1p/include" -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
In file included from alert.cpp:5:
In file included from /Users/petrus/Code/pepecoin/src/alert.h:9:
/Users/petrus/Code/pepecoin/src/serialize.h:19:10: fatal error: 'boost/type_traits/is_fundamental.hpp' file not found
#include <boost/type_traits/is_fundamental.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [obj/alert.o] Error 1
```
